import Link from "next/link";

export default function Home() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      {/* Hero */}
      <section className="flex flex-col items-center justify-center min-h-screen text-center px-4 relative overflow-hidden">
        {/* Background gradient */}
        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-transparent to-transparent pointer-events-none" />

        <div className="relative z-10 space-y-6">
          <div className="inline-block px-3 py-1 bg-primary/10 border border-primary/20 rounded-full text-xs font-medium text-primary mb-4">
            From the makers of Liceu Underground
          </div>
          <h1 className="text-5xl md:text-7xl font-display font-bold tracking-tight">
            Lexio <span className="text-primary">Underground</span>
          </h1>
          <p className="text-xl md:text-2xl text-foreground-muted font-light">
            Level up your language.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-8">
            <Link
              href="/auth/login"
              className="px-6 py-3 bg-primary text-primary-foreground font-semibold rounded-lg hover:bg-primary/90 transition neon-glow"
            >
              Get Started
            </Link>
            <Link
              href="/auth/login"
              className="px-6 py-3 bg-secondary text-secondary-foreground font-semibold rounded-lg hover:bg-secondary/80 transition"
            >
              Take Placement Test (Free)
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24 px-4">
        <div className="max-w-container mx-auto">
          <h2 className="text-3xl font-display font-bold text-center mb-12">
            Why <span className="text-primary">Lexio</span>?
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                icon: "🤖",
                title: "AI-Powered Content",
                desc: "Exercises generated by Claude, reviewed by teachers. Always fresh, always CEFR-aligned.",
              },
              {
                icon: "🔥",
                title: "Gamified Progress",
                desc: "XP, streaks, leaderboards, and badges. The kind of motivation that actually sticks.",
              },
              {
                icon: "💼",
                title: "Professional Focus",
                desc: "Business English, career advancement, real-world skills. Not gamified kindergarten.",
              },
            ].map((feature) => (
              <div
                key={feature.title}
                className="bg-card border border-border rounded-xl p-6 space-y-3 hover:border-primary/30 transition"
              >
                <div className="text-3xl">{feature.icon}</div>
                <h3 className="text-lg font-semibold">{feature.title}</h3>
                <p className="text-foreground-muted text-sm">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-24 px-4 bg-background-muted">
        <div className="max-w-container mx-auto text-center space-y-8">
          <h2 className="text-3xl font-display font-bold">
            Simple <span className="text-primary">pricing</span>
          </h2>
          <div className="grid md:grid-cols-2 gap-6 max-w-2xl mx-auto">
            <div className="bg-card border border-border rounded-xl p-6 space-y-4">
              <h3 className="text-lg font-semibold">Free</h3>
              <p className="text-3xl font-bold">R$0</p>
              <ul className="text-sm text-foreground-muted space-y-2 text-left">
                <li>✓ CEFR Placement Test</li>
                <li>✓ 3 AI Tutor messages</li>
                <li>✗ Full exercise library</li>
                <li>✗ Streaks & leaderboards</li>
              </ul>
            </div>
            <div className="bg-card border border-primary/30 rounded-xl p-6 space-y-4 relative">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-0.5 bg-primary text-primary-foreground text-xs font-semibold rounded-full">
                Popular
              </div>
              <h3 className="text-lg font-semibold">Pro</h3>
              <p className="text-3xl font-bold">R$49<span className="text-base font-normal text-foreground-muted">/mo</span></p>
              <ul className="text-sm text-foreground-muted space-y-2 text-left">
                <li>✓ Full exercise library</li>
                <li>✓ Unlimited AI Tutor</li>
                <li>✓ Streaks, XP & leaderboards</li>
                <li>✓ Progress tracking</li>
              </ul>
              <Link
                href="/auth/login"
                className="block w-full py-2 bg-primary text-primary-foreground font-semibold rounded-lg hover:bg-primary/90 transition text-center neon-glow"
              >
                Start Learning
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 text-center text-foreground-muted text-sm border-t border-border">
        <p>© {new Date().getFullYear()} Lexio Underground — by Liceu Underground</p>
      </footer>
    </main>
  );
}
