export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background p-4 md:p-8">
      <div className="max-w-3xl mx-auto space-y-8">
        <div>
          <h1 className="text-3xl font-display font-bold mb-2">Terms of Use</h1>
          <p className="text-muted-foreground text-sm">
            Last updated: April 6, 2026
          </p>
        </div>

        <div className="space-y-6 text-muted-foreground leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Lexio Underground ("the Platform"), you agree
              to be bound by these Terms of Use. If you do not agree to these
              terms, do not use the Platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">2. Description of Service</h2>
            <p>
              Lexio Underground is a gamified, AI-powered ESL (English as a Second
              Language) training platform. The service includes adaptive placement
              testing, AI-generated exercises, an AI conversational tutor, streak
              tracking, leaderboards, and the ability to schedule live classes
              with teachers.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">3. Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your
              account credentials. You agree to accept responsibility for all
              activities that occur under your account. You must provide accurate
              and complete information when creating an account.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">4. Subscription & Billing</h2>
            <p>
              Access to premium features requires an active subscription. Billing
              is handled through Stripe. Subscriptions renew automatically unless
              canceled. You may cancel at any time through the Stripe Customer
              Portal. No refunds are provided for partial billing periods.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">5. Acceptable Use</h2>
            <p>
              You may not: (a) use the Platform for any unlawful purpose;
              (b) attempt to gain unauthorized access to the Platform or its
              systems; (c) share your account credentials with others; (d) use
              automated systems to access the Platform except through provided
              APIs; (e) resell or redistribute Platform content.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">6. AI-Generated Content</h2>
            <p>
              Exercises and tutor responses are generated by artificial
              intelligence. While we strive for accuracy, AI-generated content
              may contain errors. All exercises are reviewed by human teachers
              before being made available to students. The AI tutor is not a
              substitute for professional language instruction.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">7. Intellectual Property</h2>
            <p>
              All content, branding, and code on the Platform is the property of
              Liceu Underground and is protected by intellectual property laws.
              You may not reproduce, distribute, or create derivative works from
              Platform content without express written permission.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">8. Limitation of Liability</h2>
            <p>
              Lexio Underground is provided "as is" without warranties of any
              kind. We do not guarantee that the Platform will be uninterrupted,
              error-free, or secure. To the maximum extent permitted by law, we
              shall not be liable for any indirect, incidental, or consequential
              damages arising from your use of the Platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the
              Platform at any time, with or without cause, and with or without
              notice. Upon termination, your right to use the Platform will cease
              immediately.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">10. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the Federative Republic of
              Brazil. Any disputes arising from these Terms shall be resolved in
              the courts of Brazil.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">11. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Material
              changes will be communicated via email or platform notification.
              Continued use of the Platform after changes constitutes acceptance
              of the revised Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">12. Contact</h2>
            <p>
              For questions about these Terms, contact us at{" "}
              <a
                href="mailto:talles@oliceu.com"
                className="text-primary hover:underline"
              >
                talles@oliceu.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
